openapi: 3.0.0
info:
  title: ReactNote
  description: |-
    ReactNote用RestAPI
  version: 1.0.0
servers:
  - url: http://localhost/rest
tags:
  - name: note
paths:
  /note:
    get:
      tags:
        - note
      summary: ノートの取得
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Note'
    post:
      tags:
        - note
      summary: ノートの追加
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '405':
          description: 入力が不正
  /note/{noteId}:
    get:
      tags:
        - note
      summary: ノートの取得(ID指定)
      parameters:
        - name: noteId
          in: path
          description: 取得するノートID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Note'
        '500':
          description: IDが不正
        '404':
          description: 該当するノートなし
    put:
      tags:
        - note
      summary: ノートの更新
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Note'
        required: true
      parameters:
        - name: noteId
          in: path
          description: 更新するノートのID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '500':
          description: IDが不正
        '405':
          description: 入力が不正
    delete:
      tags:
        - note
      summary: ノートの削除
      parameters:
        - name: noteId
          in: path
          description: 削除するノートID
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '500':
          description: noteIdが不正
components:
  schemas:
    Note:
      required:
        - title
        - body
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          readOnly: true
        title:
          type: string
          example: タイトル
        body:
          type: string
          example: 本文
